directories:
  output: release
  buildResources: build
appId: com.gravitydown.app
productName: GravityDown
artifactName: ${productName}-${version}.${ext}
extraResources:
  - from: ../backend/dist/gravitydown-engine.exe
    to: backend/gravitydown-engine.exe
  - from: ../backend/ffmpeg
    to: ffmpeg
win:
  target:
    - target: portable
      arch:
        - x64
    - target: nsis
      arch:
        - x64
  icon: public/icon.ico
nsis:
  oneClick: false
  allowToChangeInstallationDirectory: true
  createDesktopShortcut: true
  artifactName: ${productName}-Setup-${version}.${ext}
files:
  - filter:
      - dist/**/*
      - electron/**/*
publish:
  - provider: github
    owner: MatLumber
    repo: Mi-Downloader
electronVersion: 40.1.0
